name: enrollease
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  iconly: ^1.0.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.12
  intl: ^0.19.0
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  http: ^1.2.2
  cloud_firestore: ^5.4.5
  delightful_toast: ^1.1.0
  file_picker: ^8.1.4
  mime: ^2.0.0
  appwrite: ^13.0.0
  table_calendar: ^3.1.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_markdown: ^0.7.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logos/
    - assets/svg/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Inknut Antiqua
      fonts:
        - asset: fonts/inknut_antiqua/InknutAntiqua-Black.ttf
        - asset: fonts/inknut_antiqua/InknutAntiqua-Regular.ttf
    #         style: italic
    - family: Macondo
      fonts:
        - asset: fonts/Macondo/Macondo-Regular.ttf

    - family: Lusitana
      fonts:
        - asset: fonts/Lusitana/Lusitana-Regular.ttf
        - asset: fonts/Lusitana/Lusitana-Bold.ttf

    - family: Ma Shan Zheng
      fonts:
        - asset: fonts/Ma_Shan_Zheng/MaShanZheng-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
